//
// Created by zyc on 19-4-23.
//

#ifndef ALGORITHMS_REPEATEDSUBSTRINGPATTERN_H
#define ALGORITHMS_REPEATEDSUBSTRINGPATTERN_H

int repeatedSubstringPattern_main();

#endif //ALGORITHMS_REPEATEDSUBSTRINGPATTERN_H
