//
// Created by zyc on 3/13/19.
//

#ifndef PROJECT_REMOVENTHNODEFROMENDOFLIST_H
#define PROJECT_REMOVENTHNODEFROMENDOFLIST_H

int removeNthFromEnd_main();

#endif //PROJECT_REMOVENTHNODEFROMENDOFLIST_H
