//
// Created by zyc on 3/13/19.
//

#ifndef PROJECT_INTERSECTIONOFTWOLINKEDLISTS_H
#define PROJECT_INTERSECTIONOFTWOLINKEDLISTS_H

int getIntersectionNode_main();

#endif //PROJECT_INTERSECTIONOFTWOLINKEDLISTS_H
